 

<!-- section -->
<div class="section">
    <div class="container small">

        <div class="section-header">
            <h3>Terms and conditions</h3>
        </div>            

        <p>Facebook® is a registered trademark of Facebook Inc., 1601 S California Ave, Palo Alto, CA 94304, USA (Facebook). All rights reserved.</p>

        <p>Friends Tracker is an independent tool that simply keeps track of your Facebook friends list changes. Your current friends list is analyzed and compared with the previous saved one (if any). In this way you can find who has deleted you from Facebook.</p>

        <h4>Data Privacy Policy</h4>

        <p>This data privacy policy informs you of which personal data is being collected by Friends Tracker. It also explains how data is processed and used. The protection of your personal information is important for us. Your data is protected against unauthorized access and loss through the use of various electronic, technical, physical, administrative and contractual measures. Friends Tracker has taken the necessary technical and organizational precautions to ensure that the regulations for data privacy are respected both internally as well as by external service providers.</p>

        <h4>Collection of data</h4>

        <p>By using the Sign up feature and allowing the registration for Friends Tracker, you provide us permission to access your basic information (First Name, Last Name, Country, e-mail, Friends Tracker Password) and store them in our database. You provided us also permission to email you at any time at specified email address. Our database is not shared with any third parties.</p>

        <p>By using the Search for unfriends feature you give us permission to read your Facebook friends list page and store for an undefined period in our database your Facebook friends data (name, url).</p>

        <p>
            For your information:
            <ul>
                <li>Only names and profile urls of your Facebook friends are stored on Friends Tracker database. No other data are collected by Friends Tracker.</li>
                <li>Friends Tracker uses this information only to compare your friends list with the previous one (if any) and to show you if anyone unfriended you.</li>
                <li>Nobody can have access to your data other than you.</li>
                <li>Your information are maintained strictly private.</li>
                <li>Your friends list data will never be shared with third parties or sent to anyone.</li>
                <li>Friends Tracker tool do not alter or modify your Facebook friends list.</li>
                <li>Friends Tracker does not collect or store your Facebook login credentials. In fact, we ask you to be previously logged on Facebook before running our tool.</li>
                <li>You can ask for removal of your data from our server in every moment.</li>
            </ul>
        </p>

        <h4>Use of your data</h4>

        <p>We use your personal data:
            <ul>
                <li>to provide our services and settle payments</li>
                <li>to anonymously or pseudonymously adjust our offer to meet our users demands and improve our services</li>
                <li>to fulfill legal obligations, and in particular, to meet the requirements for preserving data</li>
            </ul>
        </p>

        <p>We also use this information to communicate with you. This includes, in particular, the provision of assistance and support as well as the provision of important contract information. Subject to your consent, we keep you informed about news, events and promotions via e-mail.</p>

        <h4>Data transfer</h4>

        <p>We will treat your data with the strictest confidentiality and will not disclose it to any third parties, unless you have given us your express permission to do so. We may however be required by law to disclose your information in certain situations (such as to an investigating authority) where the transfer takes place only within the framework required by legal conventions.</p>

        <p>In individual cases, subsidiaries, parent companies or third parties may provide services on our behalf. This mainly concerns the handling of payment transactions by external service providers (PayPal, etc.) and, in the case of default, by a debt collection company.</p>

        <h4>Google Analytics</h4>

        <p>Our website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). 
            Google Analytics uses cookies, which are text files placed on your computer, to help the website analyze how users use the site. 
            The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. 
            If, however, you activate the Anonymize IP option on this website, Google will remove the end of your IP address so it only locates you as within the member states of the European Union or other members of the European Economic Area. 
            Only in rare cases will the complete IP address be transmitted to a Google server in the USA and then shortened there. 
            Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and Internet usage. 
            The operator of this website will use information gathered via interest-related advertising as well as third-party visitor data (e.g. age, gender and interests) for the purpose of evaluation in order to find out more about the users of this website. 
            No person-related data shall be used here; only a statistical evaluation of anonymous data sets shall be carried out. 
            Google will not associate your IP address as transmitted by Google Analytics with any other data held by Google. 
            You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. 
            Furthermore, you can prohibit Google from collecting and analyzing the data generated by the cookie about your use of the website (including your IP address) by downloading and installing the browser plugin available here http://tools.google.com/dlpage/gaoptout. 
            Should you wish to adapt or prevent the analysis of your demographic or interest-based information, you can disable Google Analytics display ads and adapt the ads in the Google Display Network: https://www.google.com/settings/ads.</p>

        <!--p>Social Media Plugins</p-->

        <h4>Right of revocation, deletion of data</h4>

        <p>Even if you have given us consent to process personal data, you can withdraw this consent at any time.</p>

        <p>Friends Tracker deletes your personal data insofar as it is no longer needed or required, or if you have requested the deletion of this data. Please note that data cannot be deleted if there are legal storage requirements or this data is required by us for the billing of our services.</p>

        <h4>Refunds</h4>

        <p>By purchasing the PREMIUM License is granted to the user the use for an unlimited time (without expiry) of Friends Tracker web site and particularly of Search for unfriends feature. We do not offer refunds in any case.</p>

        <h4>Contacts</h4>

        <p>You can contact us at <a href="mailto:support@fbfriendstracker.com">support@fbfriendstracker.com</a></p>

        <p>Enjoy our tool!</p>

         
    
    </div>            
</div>
<!-- ./section -->                

